# Generated by Django 6.0.4 on 2026-04-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_arquitecturadeportiva_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolcategoria',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='rolcategoria',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
